name: Setup Node and PNPM
description: Sets up Node.js and PNPM with caching

inputs:
  os:
    required: true
    description: 'Operating system'
    default: ubuntu-latest
  node-version:
    required: true
    description: 'Node.js version'
    default: '24'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
        registry-url: 'https://registry.npmjs.org'
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - run: pnpm install --prefer-offline
      shell: bash
