packages:
  - examples/**
  - "!**/dist/**"
  - scripts
installOptions:
  preferOnline: false
  frozenLockfile: true
catalogs:
  nx:
    "@nx/eslint": 21.1.2
    nx: 21.1.2
    "@nx/cypress": 21.1.2
    "@nx/jest": 21.1.2
    "@nx/angular": 21.1.2
    "@nx/eslint-plugin": 21.1.2
    "@nx/js": 21.1.2
    "@nx/react": 21.1.2
    "@nx/vite": 21.1.2
    "@nx/rspack": 21.1.2
    "@nx/webpack": 21.1.2
    "@nx/web": 21.1.2
    "@nx/workspace": 21.1.2
    "@nx/module-federation": 21.1.2
  common:
    cross-env: ^7.0.3
    style-loader: ^4.0.0
    css-loader: ^7.1.2
    undici: ^7.5.0
    open: ^10.1.0
  swc:
    swc-loader: ^0.2.6
    "@swc/helpers": ^0.5.15
    "@swc/core": ^1.11.13
    "@swc/cli": ^0.6.0
    "@swc-node/register": ^1.10.10
  cypress:
    cypress: ^13.17.0
  jest:
    babel-jest: ^29.7.0
    jest-preset-angular: ^14.1.1
    jest-environment-jsdom: ^29.7.0
    "@types/jest": ^29.5.12
    ts-jest: ^29.2.5
    jest: ^29.7.0
  babel:
    babel-loader: ^8.2.2
    "@babel/core": ^7.25.2
    "@babel/plugin-transform-runtime": ^7.15.8
    "@babel/preset-env": ^7.15.8
    "@babel/preset-react": ^7.26.3
    "@babel/preset-typescript": ^7.10.4
    "@babel/runtime": 7.25.6
    "@babel/plugin-syntax-dynamic-import": ^7.8.3
  postcss:
    postcss: ^8.5.3
    postcss-loader: ^8.1.1
    autoprefixer: ^10.4.21
  prettier3:
    prettier: ^3.2.5
  prettier2:
    prettier: ^2.8.8
  eslint:
    "@types/eslint": ^8.56.12
    typescript-eslint: ^8.28.0
    eslint-plugin-cypress: ^4.2.0
    eslint: ^9.9.0
    "@eslint/js": ^9.9.0
    eslint-config-prettier: ^10.1.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-import: ^2.31.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react: ^7.37.4
    eslint-plugin-qwik: ^1.5.2
    eslint-plugin-react-refresh: ^0.4.19
    "@typescript-eslint/eslint-plugin": ^8.28.0
    "@typescript-eslint/parser": ^8.28.0
    "@typescript-eslint/utils": ^8.28.0
  zephyr:
    parcel-reporter-zephyr: ^0.0.53
    rollup-plugin-zephyr: ^0.0.53
    vite-plugin-zephyr: ^0.0.53
    zephyr-modernjs-plugin: ^0.0.53
    zephyr-rolldown-plugin: ^0.0.53
    zephyr-rspack-plugin: ^0.0.53
    zephyr-webpack-plugin: ^0.0.53
  rollup:
    rollup: ^4.37.0
    rollup-plugin-postcss: ^4.0.2
    "@svgr/rollup": ^8.1.0
    "@rollup/plugin-typescript": ^12.1.1
    "@rollup/plugin-babel": ^6.0.4
    "@rollup/plugin-commonjs": ^28.0.1
    "@rollup/plugin-html": ^1.0.4
    "@rollup/plugin-node-resolve": ^15.3.0
    "@rollup/plugin-replace": ^6.0.1
  module-federation:
    "@module-federation/enhanced": ^0.11.2
    "@module-federation/runtime": ^0.11.2
  typescript:
    tslib: ^2.8.1
    typescript: ^5.8.3
    "@types/node": ^22.13.13
    ts-node: ^10.9.2
  biome:
    "@biomejs/biome": ^1.9.4
  tailwind3:
    tailwindcss: ^3.4.17
    "@tailwindcss/postcss": ^3.4.17
  tailwind4:
    tailwindcss: ^4.0.3
    "@tailwindcss/postcss": "^4.1.4"
  rspack:
    "@rspack/cli": ^1.3.15
    "@rspack/core": ^1.3.15
    "@rspack/dev-server": ^1.1.3
    "@rspack/plugin-minify": ^0.7.5
    "@rspack/plugin-react-refresh": ^1.4.3
  vite5:
    vite: ^5.4.15
    vite-plugin-inspect: ^0.8.7
    "@vitejs/plugin-react": ^4.5.2
    vite-tsconfig-paths: ^4.2.1
    globals: ^15.9.0
  vite6:
    vite: ^6.3.5
    vite-plugin-inspect: ^11.1.0
    "@vitejs/plugin-react": ^4.5.2
    vite-tsconfig-paths: ^5.1.4
  webpack5:
    webpack: ^5.98.0
    webpack-cli: ^4.10.0
    webpack-dev-server: ^4.3.1
    dotenv-webpack: ^8.0.1
    html-webpack-plugin: ^5.3.2
    "@svgr/webpack": ^8.1.0
    url-loader: ^4.1.1
    css-loader: "^5.0.0"
  angular19:
    "@angular/animations": ^19.2.4
    "@angular/common": ^19.2.4
    "@angular/compiler": ^19.2.4
    "@angular/core": ^19.2.4
    "@angular/platform-browser": ^19.2.4
    "@angular/platform-browser-dynamic": ^19.2.4
    "@angular/router": ^19.2.4
    "@angular/cli": ^19.2.4
    "@angular/language-service": ^19.2.4
    "@angular/compiler-cli": ^19.2.4
    "@angular/build": ^19.2.4
    "@analogjs/vite-plugin-angular": ^1.14.1
    rxjs: ^7.8.2
    zone.js: ^0.15.0
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    react-router: ^6.30.0
    react-router-dom: ^6.30.0
    "@types/react": ^18.3.20
    "@types/react-dom": ^18.3.5
    "@types/react-router-dom": ^5.3.3
    react-refresh: ^0.16.0
    lucide-react: ^0.484.0
    "@pmmmwh/react-refresh-webpack-plugin": ^0.5.15
    "@testing-library/react": ^16.2.0
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router: ^6.30.0
    react-router-dom: ^6.30.0 // should be removed
    "@types/react": ^19.0.0
    "@types/react-dom": "^19.0.0"
    react-refresh: "^0.17.0"
    "@testing-library/react": ^16.3.0
    "@pmmmwh/react-refresh-webpack-plugin": ^0.6.0
  solid:
    solid-js: ^1.9.5
    vite-plugin-solid: ^2.11.6
  svelte:
    svelte: ^5.25.3
    svelte-check: ^4.1.5
    "@tsconfig/svelte": ^5.0.4
    "@sveltejs/vite-plugin-svelte": ^5.0.3
  turbo:
    turbo: ^2.4.4
    "@turbo/gen": ^1.13.4
  vitest1:
    vitest: ^1.3.1
    "@vitest/coverage-v8": ^1.0.4
    "@vitest/ui": ^1.6.1
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@netlify/esbuild"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - core-js-pure
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract
  - netlify-cli
  - nice-napi
  - nx
  - protobufjs
  - sharp
  - unix-dgram
  - workerd
