packages:
  - bundlers/**
  - module-federation/**
  - "!module-federation/airbnb-clone/**"
  - "!module-federation/react-vite-rspack-webpack/**"
  - frameworks/**
  - "!frameworks/react-native-metro/**"
  - "!frameworks/react-native-repack/**"
  - server/**
  - scripts

linkWorkspacePackages: true

# Fails if trusted package stops being trusted
trustPolicy: no-downgrade
# Ignores trust policies for packages older than a week
trustPolicyIgnoreAfter: 10080
# Minimum of 1 day before released packages can be installed
minimumReleaseAge: 1440
# no git/tarball dependencies, only from trusted registry
blockExoticSubdeps: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - core-js-pure
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
  - workerd
minimumReleaseAgeExclude:
  # Renovate security update: vite@7.3.2
  - vite@7.3.2
