default_platform(:ios)

platform :ios do
  desc "Builds and uploads the app to TestFlight"
  lane :testflight_distribution do
    setup_ci if ENV['CI']

    api_key = app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      is_key_content_base64: true,
      in_house: false,
    )

    match(
      type: "appstore",
      api_key: api_key,
      app_identifier: ENV['APP_IDENTIFIER'],
      readonly: ENV['CI']
    )

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"],
    )

    gym(
      scheme: "host",
      export_method: "app-store",
    )

    pilot(
      skip_waiting_for_build_processing: true,
      api_key: api_key,
    )
  end
end
