name: Code Quality Checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: true
          clean: true

      - name: Prepare repository
        uses: ./.github/actions/prepare-repo

      - name: Lint
        run: pnpm lint:ci

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: true
          clean: true

      - name: Prepare repository
        uses: ./.github/actions/prepare-repo

      - name: Typecheck
        run: pnpm typecheck
