packages:
  - examples/**
  - "!**/dist/**"
installOptions:
  preferOnline: false
  frozenLockfile: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@netlify/esbuild"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - core-js-pure
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract
  - netlify-cli
  - nice-napi
  - nx
  - protobufjs
  - sharp
  - unix-dgram
  - workerd
